/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, Font, Typograph } from "@diez/prefabs";

const creaDsmColors = {
    creaFakeRed: Color.rgba(240, 27, 27, 1),
    creaFakeDarkBlue: Color.rgba(47, 128, 237, 1),
    creaFakeLightBlue: Color.rgba(86, 204, 242, 1)
};

const creaDsmTypography = {
    creaVeryThin: new Typograph({ letterSpacing: 0, fontSize: 30, lineHeight: 35.15625, color: Color.rgba(0, 0, 0, 1), font: new Font({ name: "Roboto-Thin" }) }),
    creaLightItalics: new Typograph({ letterSpacing: 0, fontSize: 30, lineHeight: 35.15625, color: Color.rgba(0, 0, 0, 1), font: new Font({ name: "Roboto-LightItalic" }) }),
    creakFakeH1: new Typograph({ letterSpacing: 0, fontSize: 50, lineHeight: 58.59375, color: Color.rgba(0, 0, 0, 1), font: new Font({ name: "Roboto-Bold" }) })
};

export const creaDsmTokens = {
    colors: creaDsmColors,
    typography: creaDsmTypography
};
